# Generated by Django 4.2.7 on 2025-10-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_userprofile_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
