# Generated by Django 4.2.7 on 2025-10-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_tradinghabit_tradinggoal_tradingpsychology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='screenshot_after_url',
            field=models.URLField(blank=True, help_text='Local URL for after screenshot', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='screenshot_before_url',
            field=models.URLField(blank=True, help_text='Local URL for before screenshot', null=True),
        ),
    ]
