# Generated by Django 4.2.7 on 2025-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_add_supabase_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='setup_type',
            field=models.CharField(choices=[('BREAKOUT', 'Breakout'), ('PULLBACK', 'Pullback'), ('NEWS_BASED', 'News-based'), ('TECHNICAL', 'Technical Analysis'), ('FUNDAMENTAL', 'Fundamental Analysis'), ('SCALPING', 'Scalping'), ('SWING', 'Swing Trading'), ('POSITION', 'Position Trading'), ('SUPPORT_RESISTANCE', 'Support/Resistance'), ('FIBONACCI', 'Fibonacci (Discount & Premium Zone)'), ('VOLUME_SPIKE', 'Volume Spike'), ('LIQUIDITY_GRAB', 'Liquidity Grab'), ('ORDER_BLOCK', 'Order Block'), ('FAIR_VALUE_GAP', 'Fair Value Gap'), ('BREAK_OF_STRUCTURE', 'Break of Structure'), ('CHANGE_OF_CHARACTER', 'Change of Character'), ('MARKET_MAKER_MODEL', 'Market Maker Model'), ('OTHER', 'Other')], help_text='Type of setup used', max_length=20),
        ),
    ]
