# Generated by Django 4.2.7 on 2025-10-17 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_trade_setup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='capital_invested',
            field=models.FloatField(default=0, help_text='Total capital invested in this trade', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trade',
            name='entry_premium',
            field=models.FloatField(blank=True, help_text='Premium price at entry (for options/futures)', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_premium',
            field=models.FloatField(blank=True, help_text='Premium price at exit (for options/futures)', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='risk_reward_ratio',
            field=models.FloatField(blank=True, help_text='Risk/Reward ratio for this trade', null=True),
        ),
    ]
