# Generated by Django 4.2.7 on 2025-10-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_trade_capital_invested_trade_entry_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='capital_invested',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='risk_reward_ratio',
        ),
    ]
