# Generated by Django 4.2.7 on 2025-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_remove_trade_capital_invested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='entry_premium',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_premium',
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PARTIAL', 'Partial')], default='CLOSED', help_text='Current status of the trade', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='setup_type',
            field=models.CharField(choices=[('BREAKOUT', 'Breakout'), ('PULLBACK', 'Pullback'), ('NEWS_BASED', 'News-based'), ('TECHNICAL', 'Technical Analysis'), ('FUNDAMENTAL', 'Fundamental Analysis'), ('SCALPING', 'Scalping'), ('SWING', 'Swing Trading'), ('POSITION', 'Position Trading'), ('LIQUIDITY_SWEEP', 'Liquidity sweep setups'), ('ORDER_BLOCK', 'Order block trades'), ('FAIR_VALUE_GAP', 'Fair Value Gap trades'), ('BREAKER_BLOCK', 'Breaker block setups'), ('MITIGATION_BLOCK', 'Mitigation block trades'), ('MARKET_STRUCTURE', 'Market structure breaks'), ('BOS_CHOCH', 'Break of Structure / Change of Character'), ('REVERSAL', 'Reversal setups'), ('FIBONACCI', 'Fibonacci retracements/extensions'), ('SUPPORT_RESISTANCE', 'Support/Resistance levels'), ('OTHER', 'Other')], help_text='Type of setup used', max_length=20),
        ),
    ]
