# Generated by Django 4.2.7 on 2025-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_remove_trade_entry_premium_remove_trade_exit_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_status',
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'date'], name='journal_tra_user_id_4c00ad_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'profit_loss'], name='journal_tra_user_id_edddc8_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'symbol'], name='journal_tra_user_id_96ac05_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'setup_type'], name='journal_tra_user_id_444620_idx'),
        ),
    ]
